apiVeriosn: v1
kind: service
metadata:
  name: db-svc
  labels:
    env: dev
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - name: db-port
      targetPort: 3306
      port: 32100
      protocol: TCP
  selector:
    db: std-db